name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body : |
            This is an automated release, see [the changelog](https://github.com/tom-webber/advent-of-code/blob/master/CHANGELOG.md) for changes
        env:
          GITHUB_TOKEN: ${{ github.token }}
