name: Update README

on:
  push:
    branches:
      - master
    paths:
      - 'src/adventofcode/year_*/**'
      - 'src/adventofcode/scripts/generate_readme.py'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Generate new README
      run: generate-readme
    - name: Commit new README
      run: |
        git config --global user.name 'Tom Webber'
        git config --global user.email 'tom-webber@users.noreply.github.com'
        [[ -n $(git status -s) ]] && git commit -am "docs: update README"
        git push
